### ISSUE TITLE
Question: Problem with request: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by ntrabue** [Sunilosys/Loan-Officer-Connect-Alexa-Skill-Set#1]
Hello, first of all thank you for this guide. I'm very new to Alexa Skills, Lambda, Developer Connect AND node in general lol.

I notice in your index.js file that you have some variables that are process environment variables. When I don't define those in Lambda it gives me an error problem with request: connect ECONNREFUSED 127.0.0.1:443. 

When I do define these env variables I'm getting the error:
problem with request: getaddrinfo ENOTFOUND
api.elliemae.com/encompass/v1
api.elliemae.com/encompass/v1:443

Honestly I was taking a shot in the dark when defining these variables. I set 
EBS_API_URL = api.elliemae.com/encompass/v1
OPEN_API_URL = api.elliemae.com

Unfortunately this is my last resort after a couple of hours of googling trying to understand the issue. Thank you in advance!

**Comment by Sunilosys** [comment]
Hi Nick,
Loan officer connect skill set is specifically designed for someone who has access Encompass (Our Loan Originator Software) and Developer Connect. Please let me know if you have access to use Developer Connect. I can definitely help you with building your own Loan Officer Connect Skill. 

Thanks,
Sunil

**Comment by ntrabue** [comment]
Hello, I do indeed have access to Developer Connect. I followed your guide as best I could and cross-referenced with the guide here: https://docs.developer.elliemae.com/reference#alexa. I think Lambda has gone through some changes since this was originally posted so I'm not 100% sure I followed it perfectly. 

I am able to access the skill on my alexa app. I'm able to log in and authenticate successfully with my loan officer connect credentials. When I test some utterances, the Help utterance works and logout says I've successfully logged out but I'm not convinced it actually kills my session.

Looking at Cloudwatch, I see that my requests are logging the "onSessionStarted" and "onIntent" lines successfully but the last line it logs is
`problem with request: getaddrinfo ENOTFOUND api.elliemae.com/encompass/v1 api.elliemae.com/encompass/v1:443`

I'm assuming this has to do with the process.env.EBS_API_URL I set in Lambda which I listed in my OP since I had no idea what it might be or maybe I'm doing this all wrong :) lol

**Comment by Sunilosys** [comment]
Hi Nick,
First of all , Thank you for using my guide. I wish I could have put more details there. This skill was done a few months back. That time , we didn't have many dev connect APIs. So I was using the internal apis using our internal URI. You should use OPEN API URI instead of EBS_API_URL. For example instead of using EBS_API_URL to get the loan details, you should use OPEN_API_URL and use the pipeline search API from open API. If you can give me a few days, I will change the skill to use only dev connect APIs. Thank you again for using my guide. Since you got the authentication working , you are awesome :-).

**Comment by ntrabue** [comment]
Ahhh. That makes a lot of sense and I think you actually improved my understanding of the code there. Simply replacing EBS_API_URL with OPEN_API_URL won't do the trick because they probably accept different parameters as well which explains my new error: 
`{"errorMessage":"Exception: Error: `value` required in setHeader(\"elli-session\", value)."}`
as bearer_token no longer appears to be in the response of the introspection call. 

Could still be totally off-base but I will happily wait... or, if I have time I'll play with it and see if I can make it work lol :) Please do not put any kind of rush on this. This is a side-project for me and I won't even be telling our loan officers until January. Just wanted to get a head-start. Thank you for your help @Sunilosys

**Comment by Sunilosys** [comment]
Yes. you are right. Contract and Authentication are different for Dev Connect API. If you get some time, please check my Automated Loan Officer Connect demo using Google Home https://www.youtube.com/watch?v=VGMMFx2qoaM

**Comment by ndandan** [comment]
Any luck with getting this connected with the Dev Connect API?

**Comment by ntrabue** [comment]
I have not had any time to play with this, @ndandan sorry. I might have some time next week to play with it if @Sunilosys doesn't get around to it.

**Comment by Sunilosys** [comment]
Hey guys, I haven't got chance to look at it. I promise I will get it done this weekend. You will have it by Monday :-)

**Comment by ndandan** [comment]
Thanks @Sunilosys and @ntrabue

**Comment by ntrabue** [comment]
Hey there, @Sunilosys I've tried with the latest commit and now I'm getting "non-200 response" when I launch the skill... any ideas? I have my environment variables set.

**Comment by jenpringbell1983** [comment]
I'm getting the same response

**Comment by Sunilosys** [comment]
@ntrabue @jenpringbell1983 Thank you for the comments. Sorry for the late reply. I am very busy lately. I need to make the changes to the code to use only Dev Connect APIs. Previously I had used some Internal APIs for my initial implementation. I will have a working version of the code using only Dev Connect API sometime this week.

**Comment by Sunilosys** [comment]
@ntrabue @jenpringbell1983 Sorry for the delayed response. Finally made the changes to use only Dev connect APIs. I had to remove some of the functionality such as product pricing search and rate lock expiration search for current week.

**Comment by ntrabue** [comment]
Thank you @Sunilosys! I'll give it a test tomorrow!
